### ISSUE TITLE
mposCompatibility.js issues

### ISSUE THREAD

**Issue by Marty19** [sigwo/unified-node-open-mining-portal#13]
Thanks for all you efforts to bring UNOMP up to date but I have noticed the following:

 - mposCompatibility.js is pointing at he wrong table names to integrate with mpos, should be `pool_worker` and `accounts` instead of `workers` and `user`
 - there is no coding to handle the shares from merged mining.

Any plans to correct this?

Thanks.

**Comment by sigwo** [comment]
confirmed merged mining works with ONE aux coin when in MPOS mode
