### ISSUE TITLE
trying to pull git

### ISSUE THREAD

**Issue by Infernoman** [sigwo/unified-node-open-mining-portal#18]
hey just have some questions here about getting my website onto server without screwing too much up. like the admin page. i know i will have to manually add the pages i use again into website.js but as for importing my files theres a lot of new files im not familiar with, so i wondered if you were interested in helping out a bit.

**Comment by sigwo** [comment]
The admin page is still not operational. I haven't done much with the front end, as I'm concentrating on the merged mining share capture and reporting features. Mostly, the new files are for the front end you see when starting the web server. If you are putting your own template, you can basically replace any of the .css files and add your custom .js files. It shouldn't kill anything.

I am trying to get some more folks on this repo so we can resurrect this software :)

**Comment by Infernoman** [comment]
beleive me i've been trying to do that forever ! im glad someone finally got started on it again. my database mostly runs on bash scripts that do the processing for the multipool but other than that im running pretty much the same thing. the CLI has been updated in this version though correct? so i dont have to restart the pool manually whenever making changes to configs?

**Comment by Infernoman** [comment]
yepp looks like it is. i got those shitcoins added into profitswitch and changed the algo calculations for sha256 as you noticed. im working on updating my client now with UNOMP. what id like to do is be able to add EMC2 and freicoin since they have both been around for a while but freicoin requires a different block template as seen here https://github.com/freicoin/stratum-mining/commit/bc0abacf5313113e5f97ecfa058f6c8a13794518 and EMC2 requires a donation address but im not sure whether or not it can be defined in the payout addresses of the json file. https://github.com/einsteinium/EMC2-Stratum-Mining

**Comment by sigwo** [comment]
Bash is all good dude :) Feel free to contribute any code as you see fit, node, bash, or any other flavor. If it gets pushed as non-node.js code, we can try to refactor it to make this one slick package.

As for the donation, I set the address as a 
```json
"rewardRecipients": {
        "n37vuNFkXfk15uFnGoVyHZ6PYQxppD3QqK": 1.5,  //make this the donation address/amount
```
and that seemed to work on GRE and DMD.

**Comment by Infernoman** [comment]
hmm interesting. alright well im going to have to test that out again. and see what percentage of each block needs to go towards EMC2 donations. also i just pushed another update to profitswitch.js and added some how to in there if you wanted to add that to the website.

**Comment by sigwo** [comment]
Cool. Please be sure to open issues for enhancements or unrelated errors. :smile:

**Comment by Infernoman** [comment]
no problem :) ill work on doing that for the next one. im going to sned in the bash scripts for adding coin prices to redis and sending coins to exchanges. and if development continues ill maybe even throw a quick guide and some payment scripts for a proper multipool. im just putting the basics into it for now. maybe they will be useful for the website you currently have.

**Comment by sigwo** [comment]
Excellent! I 100% plan on continuing the efforts here. For the multipool scripting, let's make a directory 'multipool' for that.

**Comment by Infernoman** [comment]
i made a few more additions to my clone on github. i added the multipool folder and created a few of the scripts. just missing the one for payouts. and of course the notorious exchange script for buying and selling coins.

**Comment by sigwo** [comment]
Awesome! Throw it in a PR when you get a chance. 

When you open a PR, just add the comments to the PR, as Git will track PR's and comments. No issue needed when doing straight PR.

**Comment by AltNuts** [comment]
@Infernoman I am currently working on an integration myself. I have the basic layout added and have been able to add custom tables to display the data. Not sure what all you are needing help with.
