### ISSUE TITLE
Worker Stats

### ISSUE THREAD

**Issue by Infernoman** [sigwo/unified-node-open-mining-portal#22]
Since most multipools don't like to show which coins are being mined i thought that sorting the workers into algos aswell as coins would be a benefit. i was looking at the code in stats.js but im not quite capable of making that change. was wondering if you could take a look into it. currently each algo has a workercount under "portalstats[algo].workers" i think that should be changed to workercount and an extra portalstats[algo].workers[worker] added in.

**Comment by Infernoman** [comment]
after that the code will be accessible through dot.js on the website using '{{=it.stats.algo[algo].workers[worker]}}'

**Comment by sigwo** [comment]
I believe this is corrected. From the test pool [uNOMP](http://pool.unomp.org/api/algo_stats). If this is what you wanted, please close the comment. Thanks! :)

**Comment by Infernoman** [comment]
Close ! but not quite what im looking to do is take the entry from portalstats.pools[pool].workers[worker] and add it to algo_stats api OR create a new api so we are able to provide a quick and responsive chart for the miner stats page. the QUICKEST option but also most complicated is to create an API for EACH of the workers instead of clumping them together.

**Comment by sigwo** [comment]
After the discussion in Slack, I understand what you are looking for. Did PF's script work?
