### ISSUE TITLE
Mining.extranonce.subscribe

### ISSUE THREAD

**Issue by Infernoman** [sigwo/unified-node-open-mining-portal#23]
Mintsy and a few of the other asic technologies are starting to use a feature called mining.extranonce.subscribe currently atleast in the nomp repo it is not supported this would have to do more with the node module stratum-pool for nomp and stratum-merged for unomp. 
This will also give us support for changing the extranonce for the miners that allow it on the fly and no longer have to re establish a connection
https://github.com/int6/hpool-stratum/issues/1

currently the error provided when a miner with that stratum implementation tried to connect is 
 Unknown stratum method from (unauthorized) [79.109.251.102]: mining.extranonce.subscribe

here is the file i am referencing 
https://github.com/sigwo/node-merged-pool/blob/master/lib/stratum.js#L62-L102

**Comment by sigwo** [comment]
Gonna move this to the [repo](https://github.com/sigwo/node-merged-pool/blob/master/lib/stratum.js#L62-L102)

**Comment by frndxyz** [comment]
@sigwo  you ignore it or build this in future? because i havent seen it there.
