### ISSUE TITLE
erron when init.js

### ISSUE THREAD

**Issue by napoleon2121** [sigwo/unified-node-open-mining-portal#26]
[2015-03-25 18:39:32.223] [INFO] [default] - New Relic
[2015-03-25 18:39:32.231] [INFO] [default] - POSIX Not Installed
[2015-03-25 18:39:32.231] [DEBUG] [default] - POSIX Connection Limit (Safe to ignore) POSIX module not installed and resource (connection) limit was not raised
[2015-03-25 18:39:32.232] [INFO] [default] - Run Workers

/root/nomp/init.js:139
        for (var i=0; i < poolOptions.auxes.length; i++)
                                           ^
TypeError: Cannot read property 'length' of undefined
    at /root/nomp/init.js:139:37
    at Array.forEach (native)
    at buildPoolConfigs (/root/nomp/init.js:135:21)
    at init (/root/nomp/init.js:447:19)
    at Object.<anonymous> (/root/nomp/init.js:459:3)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)

ideas ?

**Comment by sigwo** [comment]
do you have auxes listed?

**Comment by napoleon2121** [comment]
my config file is like this for darkcoin.

    "enabled": true,
    "coin": "darkcoin.json",

    "address": "XtTZot5TCNMVrokxrpwUw4iARRJ6qPvy2T",

    "rewardRecipients": {
        "XuGJpGLNgQPknB3VoWHrPDL6EwkXHDxQBr": 1.5,
        "22851477d63a085dbc2398c8430af1c09e7343f6": 0.1
    },

    "paymentProcessing": {
        "enabled": true,
        "paymentInterval": 20,
        "minimumPayment": 70,
        "daemon": {
            "host": "127.0.0.1",
            "port": 9332,
            "user": "napoleon2121",
            "password": "napo31223122"
        }
    },

    "ports": {
        "3008": {
            "diff": 0.01
        },
        "3032": {
            "diff": 0.01,
            "varDiff": {
                "minDiff": 0.01,
                "maxDiff": 1,
                "targetTime": 15,
                "retargetTime": 90,
                "variancePercent": 30
            }
        },
        "3256": {
            "diff": 0.01
        }
    },

    "daemons": [
        {
            "host": "127.0.0.1",
            "port": 9332,
            "user": "napoleon2121",
            "password": "napo31223122"
        }
    ],

    "p2p": {
        "enabled": true,
        "host": "127.0.0.1",
        "port": 19333,
        "disableTransactions": true
    },


    "mposMode": {
        "enabled": false,
        "host": "127.0.0.1",
        "port": 3306,
        "user": "me",
        "password": "mypass",
        "database": "ltc",
        "checkPassword": true,
        "autoCreateWorker": false
    }

}

**Comment by napoleon2121** [comment]
it's the only coin i installed for now. it's brand new service for testing

**Comment by sigwo** [comment]
Start here:
https://github.com/sigwo/unified-node-open-mining-portal/blob/master/pool_configs/litecoin.json.example#L5

**Comment by napoleon2121** [comment]
yea what is auxiliery coins. at the example you hav 2 3 coins to daemon. i hav only one atm. what exacly aux does i didn't go at the example. :(

**Comment by sigwo** [comment]
AUXPoW coins are merged-mined coins. That capability defines what is different between this repo and the original [NOMP](https://github.com/zone117x/node-open-mining-portal). The regular NOMP is easier and more 'ready' for novice pool operators. There are a *lot* of moving parts in the UNOMP software at the moment. As stated on the [README.md](https://github.com/sigwo/unified-node-open-mining-portal/blob/master/README.md), this is not production ready software.

**Comment by napoleon2121** [comment]
i know that is what i like and i want test it out. i really like it.
