### ISSUE TITLE
profitSwitch.js

### ISSUE THREAD

**Issue by sigwo** [sigwo/unified-node-open-mining-portal#28]
```bash
TypeError: Cannot call method 'hasOwnProperty' of undefined
    at /home/an/unomp/unified/libs/profitSwitch.js:487:36
    at Array.forEach (native)
    at /home/an/unomp/unified/libs/profitSwitch.js:485:51
    at /home/an/unomp/unified/node_modules/async/lib/async.js:610:21
    at /home/an/unomp/unified/node_modules/async/lib/async.js:249:17
    at iterate (/home/an/unomp/unified/node_modules/async/lib/async.js:149:13)
    at /home/an/unomp/unified/node_modules/async/lib/async.js:160:25
    at /home/an/unomp/unified/node_modules/async/lib/async.js:251:21
    at /home/an/unomp/unified/node_modules/async/lib/async.js:615:34
    at /home/an/unomp/unified/libs/profitSwitch.js:442:25
[2015-03-31 13:55:49.122] [ERROR] [default] - Master Profit Profit switching process died, spawning replacement...
```

**Comment by Infernoman** [comment]
Hey sigwo is this happening when launching the pool or while trying to check the profitability for the other coins for the coin change?

**Comment by sigwo** [comment]
This happens when starting the pool. I've not yet instituted the multipooling yet. That is this week's task. Was there an update for your multipool configs that changed code in profitSwitch.js?

**Comment by Infernoman** [comment]
hmm thats weird. the only changes to the profitswitch.js was to add in the .txt files for each of the algos in static/algo.txt and for the coins that have the weird coinbasevalues, in profitswitch.js did you notice there was a portion to input API keys for the exchanges? it seems like its failing around the point it is trying to get exchange info. another quesiton is did you add each of your algos to Coin_Algos and coins your mining to Coin_Names and Coin_Names_Algo in redis?

**Comment by sigwo** [comment]
I've not done the adding to redis yet. That will hopefully be tonight. I rebuilt my environment this last weekend so I'm working slower than I'd like. I'll get those added in and see if I still get the error.

**Comment by sigwo** [comment]
Error still present, digging into profitSwitch.js....

**Comment by Moxnatiy** [comment]
hi , (sorry for my english) i fix this error, but needs edit many files

**Comment by sigwo** [comment]
Fork the repo, make your changes that you have made to fix the error, and then submit a 'Pull Request'. I'll review and merge into this repo, and then push to the master uNOMP repo. :)

**Comment by sigwo** [comment]
Ref https://github.com/sigwo/unified-node-open-mining-portal/commit/e70347162d442af19b4f803111d9cef713e3d3d3
