### ISSUE TITLE
startup Problem

### ISSUE THREAD

**Issue by micheldaniel** [sigwo/unified-node-open-mining-portal#32]
If i do nade init.js than i have this problem

http://hastebin.com/xojudibuzu.rb

**Comment by 9cat** [comment]
you missed that quotation "

**Comment by micheldaniel** [comment]
but how can i fix it?

**Comment by 9cat** [comment]
"redis":{"host":"127.0.0.1","port":6379,"db":root,"pass

change to 

"redis":{"host":"127.0.0.1","port":6379,"db":"root","pass

**Comment by micheldaniel** [comment]
new error! :-(

http://hastebin.com/oyuladohib.rb

this is my code

http://hastebin.com/okewedazaq.cpp

**Comment by sigwo** [comment]
Change "root" in your redis config to "0" and remove password unless you have one configured in redis.conf. 

-SG

**Comment by sigwo** [comment]
If you have any further issues, please open a ticket in (UNOMP)[https://github.com/UNOMP/unified-node-open-mining-portal]
