### ISSUE TITLE
does this fork can pay to miner now

### ISSUE THREAD

**Issue by microlost** [sigwo/unified-node-open-mining-portal#33]
Hi,sigwo,does your repo here can auto pay to miner now?

**Comment by sigwo** [comment]
Yes, it autopays to the miner in the coin they are mining. MERGED mined coins DO NOT payout, ONLY to the wallet on the server.

**Comment by microlost** [comment]
I have build a merged pool(LTC&DOGE) with this repo, and have fond 3 LTC blocks with 200 + confirmations, but they are all in pending stake,also can't pay to the miner.

BTW,can I create tickets for issues in this repo ,or better go to: https://github.com/UNOMP/unified-node-open-mining-portal

**Comment by sigwo** [comment]
The repo you just linked is the repo I asked you to open the issue :) This repo is the 'testing repo'. There has been a lot of moving parts, and UNOMP invited me to join that repo, so that is why there is a bit of confusion.

Please open this ticket in the UNOMP repo. Thanks!
