### ISSUE TITLE
a Question

### ISSUE THREAD

**Issue by Caberhagen** [sigwo/unified-node-open-mining-portal#37]
Hi
As first thanks for your work.
i test youre repo form merged mining. 
Now just one question:
How can i setup a coin without merged. Like earthcoin or so.

**Comment by sigwo** [comment]
Make your pools' config like this for the "auxes" section.

"auxes": [ {} ]

That should do the trick.

**Comment by sigwo** [comment]
Apologies. It is 
```bash
    "auxes": [
    ],
```

**Comment by Caberhagen** [comment]
thx it works..
