### ISSUE TITLE
question for network stats

### ISSUE THREAD

**Issue by Caberhagen** [sigwo/unified-node-open-mining-portal#43]
Hi

i try to get more stats to the webpage.
Networkstats like Nethashps and netdiff atm.
but i am not a great dev. just leran some skills now.
Can anyone give me some hints how i can solve it???

thx for any help....

**Comment by sigwo** [comment]
Some helpful things are found here: http://expressjs.com/starter/basic-routing.html

Also read up on webdis and redis-commander. :)
